# Generated by Django 4.0.10 on 2024-10-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
